//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HunterNotebook2.StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized_FindDialogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized_FindDialogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HunterNotebook2.StringResources.Localized_FindDialogStrings", typeof(Localized_FindDialogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Regular Expressions.
        /// </summary>
        internal static string FindDialog_Checkbox_AllowUnfilteredExpression {
            get {
                return ResourceManager.GetString("FindDialog_Checkbox_AllowUnfilteredExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Matters.
        /// </summary>
        internal static string FindDialog_Checkbox_CaseMatters {
            get {
                return ResourceManager.GetString("FindDialog_Checkbox_CaseMatters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the to again when we reach the end.
        /// </summary>
        internal static string FindDialog_Checkbox_RestartAtTop {
            get {
                return ResourceManager.GetString("FindDialog_Checkbox_RestartAtTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find First.
        /// </summary>
        internal static string FindDialog_FindFirstButtonTitle {
            get {
                return ResourceManager.GetString("FindDialog_FindFirstButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Last.
        /// </summary>
        internal static string FindDialog_FindLastButtonTitle {
            get {
                return ResourceManager.GetString("FindDialog_FindLastButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        internal static string FindDialog_FindNextButtonTitle {
            get {
                return ResourceManager.GetString("FindDialog_FindNextButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no matches for that..
        /// </summary>
        internal static string FindDialog_NoResultsMessage {
            get {
                return ResourceManager.GetString("FindDialog_NoResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Wildcards.
        /// </summary>
        internal static string FindFialog_Checkbox_AllowWildcard {
            get {
                return ResourceManager.GetString("FindFialog_Checkbox_AllowWildcard", resourceCulture);
            }
        }
    }
}
