//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HunterNotebook2.StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized_ChooseFontDialogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized_ChooseFontDialogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HunterNotebook2.StringResources.Localized_ChooseFontDialogStrings", typeof(Localized_ChooseFontDialogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick brown dog danced a gig over a fence.
        /// </summary>
        internal static string ChooseFont_ExampleString {
            get {
                return ResourceManager.GetString("ChooseFont_ExampleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not show preview for selected font.
        /// </summary>
        internal static string ChooseFont_FontPreviewFailure {
            get {
                return ResourceManager.GetString("ChooseFont_FontPreviewFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Affect Text.
        /// </summary>
        internal static string ChooseFont_HowToHandleText {
            get {
                return ResourceManager.GetString("ChooseFont_HowToHandleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affect All Text.
        /// </summary>
        internal static string ChooseFont_TextAction_AllText {
            get {
                return ResourceManager.GetString("ChooseFont_TextAction_AllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affect Selected Text.
        /// </summary>
        internal static string ChooseFont_TextAction_SelectedText {
            get {
                return ResourceManager.GetString("ChooseFont_TextAction_SelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Font to Use.
        /// </summary>
        internal static string ChooseFont_Titlebar {
            get {
                return ResourceManager.GetString("ChooseFont_Titlebar", resourceCulture);
            }
        }
    }
}
